[platformio]
default_envs = lora_rx

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    jgromes/RadioLib @ ^6.6.0
build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:lora_tx]
build_flags =
    ${env.build_flags}
    -D LORA_TEST_TX

[env:lora_rx]
build_flags =
    ${env.build_flags}
    -D LORA_TEST_RX
